# Darwin x86_64, with gcc and gfortran, NetCDF support, and built in Maths libraries
CFLAGS = -DHAVE_NETCDF -DNETCDF4 -I/opt/local/include -fPIC -O3
CC = gcc
FC = gfortran
LD = gcc
SYSLIBS = -L/opt/local/lib -lnetcdf -lhdf5 -lhdf5_hl -framework Accelerate