
uname := $(shell uname)

NM = nm
AR = ar
RANLIB = ranlib

# Darwin x86_64, with gcc and gfortran, NetCDF support, and built in Maths libraries
ifeq ($(uname),Darwin)
  CFLAGS = -DHAVE_NETCDF -DNETCDF4 -I/opt/local/include -fPIC -O3
  CC = gcc
  FC = gfortran
  LD = gcc
  SYSLIBS = -L/opt/local/lib -lnetcdf -lhdf5 -lhdf5_hl -framework Accelerate
endif

# GNU/Linux x86_64
ifeq ($(uname),Linux)
  CFLAGS = -DHAVE_NETCDF -DNETCDF4 -fPIC -O3
  CC = gcc
  FC = gfortran
  LD = gcc
  SYSLIBS = -lnetcdf -llapack -lblas -lpthread
endif

# if none of the above matches then we hope for the best...
